id: rescue-workflow
namespace: aras.rescue

inputs:
  - id: alertId
    type: STRING
  - id: animalType
    type: STRING
  - id: injuryLocation
    type: STRING
  - id: severity
    type: INT
  - id: ngoEmail
    type: STRING
  - id: imageUrl
    type: STRING
  - id: latitude
    type: STRING
  - id: longitude
    type: STRING

pluginDefaults:
  - type: io.kestra.plugin.notifications.mail.MailSend
    values:
      host: smtp.resend.com
      port: 465
      username: resend
      password: YOUR_RESEND_API_KEY_HERE
      transportStrategy: SMTPS

tasks:
  - id: sendEmail
    type: io.kestra.plugin.notifications.mail.MailSend
    from: onboarding@resend.dev
    to: "{{inputs.ngoEmail}}"
    subject: "🚨 URGENT: Injured {{inputs.animalType}} Needs Rescue"
    htmlTextContent: |
      <html>
        <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
          <div style="max-width: 600px; margin: 0 auto; padding: 20px; border: 2px solid #ef4444; border-radius: 8px;">
            <h2 style="color: #ef4444; margin-top: 0;">🐾 Animal Rescue Alert</h2>
            
            <div style="background: #fef2f2; padding: 15px; border-radius: 6px; margin: 20px 0;">
              <h3 style="margin-top: 0; color: #991b1b;">Alert Details</h3>
              <p><strong>Animal Type:</strong> {{inputs.animalType}}</p>
              <p><strong>Injury Location:</strong> {{inputs.injuryLocation}}</p>
              <p><strong>Severity Level:</strong> {{inputs.severity}}/5</p>
              <p><strong>GPS Coordinates:</strong> {{inputs.latitude}}, {{inputs.longitude}}</p>
            </div>
            
            <div style="margin: 20px 0;">
              <h3>Animal Photo</h3>
              <img src="{{inputs.imageUrl}}" alt="Injured Animal" style="max-width: 100%; height: auto; border-radius: 6px; border: 1px solid #ddd;">
            </div>
            
            <div style="background: #f0fdf4; padding: 15px; border-radius: 6px; margin: 20px 0;">
              <p style="margin: 0;"><strong>📍 View Location on Map:</strong></p>
              <a href="https://www.google.com/maps?q={{inputs.latitude}},{{inputs.longitude}}" 
                 style="display: inline-block; margin-top: 10px; padding: 10px 20px; background: #16a34a; color: white; text-decoration: none; border-radius: 4px;">
                Open in Google Maps
              </a>
            </div>
            
            <p style="font-size: 12px; color: #666; margin-top: 30px;">
              This alert was automatically generated by the A.R.A.S (Animal Rescue Alert System).
              Please respond as soon as possible.
            </p>
          </div>
        </body>
      </html>
